### ISSUE TITLE
Neovim freezes after ' feat(hack): add hack to actually disable file watching' (8e29dbdc98b0f1c6dddd719ce6d1efcd1e7701c7)

### ISSUE THREAD

**Issue by AdamGoto** [seblj/roslyn.nvim#10]
After commit 8e29dbdc98b0f1c6dddd719ce6d1efcd1e7701c7 neovim freezes after startup, even on the generated console template that only contains 1 file with 1 line of code.

**Comment by seblj** [comment]
Woops, sorry. Should be fixed now

**Comment by AdamGoto** [comment]
It is, thank you for the quick fix!
