### ISSUE TITLE
The semantic tokens wiki entry needs to be updated for newer neovim versions

### ISSUE THREAD

**Issue by kmoschcau** [seblj/roslyn.nvim#103]
Newer versions of neovim (I don't remember the exact switch moment.) `vim.lsp.Client.request` is now a method on the metatable, so the semantic highlighting snippet needs to be updated to work with it.

```lua
--- @param client vim.lsp.Client the LSP client
local function monkey_patch_semantic_tokens(client)
  -- NOTE: Super hacky... Don't know if I like that we set a random variable on
  -- the client Seems to work though ~seblj
  if client.is_hacked then
    return
  end
  client.is_hacked = true

  -- let the runtime know the server can do semanticTokens/full now
  client.server_capabilities =
    vim.tbl_deep_extend("force", client.server_capabilities, {
      semanticTokensProvider = {
        full = true,
      },
    })

  -- monkey patch the request proxy
  local request_inner = client.request
  function client:request(method, params, handler, req_bufnr)
    if method ~= vim.lsp.protocol.Methods.textDocument_semanticTokens_full then
      return request_inner(self, method, params, handler)
    end

    local target_bufnr = vim.uri_to_bufnr(params.textDocument.uri)
    local line_count = vim.api.nvim_buf_line_count(target_bufnr)
    local last_line = vim.api.nvim_buf_get_lines(
      target_bufnr,
      line_count - 1,
      line_count,
      true
    )[1]

    return request_inner(self, "textDocument/semanticTokens/range", {
      textDocument = params.textDocument,
      range = {
        ["start"] = {
          line = 0,
          character = 0,
        },
        ["end"] = {
          line = line_count - 1,
          character = string.len(last_line) - 1,
        },
      },
    }, handler, req_bufnr)
  end
end
```

The main difference is the method definition to `function client:request(...)` and passing `self` to `request_inner`.

**Comment by StefanFanaru** [comment]
Nice work @kmoschcau! 
How do you activate semantic tokens in the code though? I can't find a way. All may code has only the default three sitter colours.

**Comment by kmoschcau** [comment]
@StefanFanaru have a look [here](https://github.com/kmoschcau/nvim-config/blob/main/lua/plugin-management/plugins/lsp/roslyn.lua) for my roslyn setup. For my general lazy entrypoint for LSPs, have a look [here](https://github.com/kmoschcau/nvim-config/blob/main/lua/plugin-management/plugins/nvim-lspconfig.lua) (this latter file pulls in the previously linked one).

**Comment by yavorski** [comment]
Hi, is this working only on nvim nightly 0.11? 
It currently doesn't work for me in nvim 0.10.4 but it works on nightly?

**Comment by yavorski** [comment]
I have found the [diff](https://github.com/seblyng/roslyn.nvim/wiki/Home/_compare/a89e0fb1bf3174bda6aa0f4ec753074b5c4e1256...d9fb38267849ea1ed457e4cf90566b59718188e5), previous version works fine in v0.10.4.
Looking forward too see this included in the plugin itself : ) Thank you!

**Comment by seblyng** [comment]
Thanks for the diff, that makes it easier for me to just paste it in.

I will probably never include it in the plugin itself as a hack though, and will instead just have this in the wiki until neovim supports that lsp method

**Comment by PaddiM8** [comment]
I added support for textDocument/semanticTokens/full to roslyn so this will soon work out of the box
