### ISSUE TITLE
Error when Attempting to Resolve Code Action - Bufnr: Expected Number, got Function

### ISSUE THREAD

**Issue by blamcodes** [seblj/roslyn.nvim#104]
Would appreciate some help and guidance on whether this issue is from the plugin itself or from my configs.

This error occurs when I want to perform the code action of Fully Qualifying a method. 

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/client.lua:643: bufnr: expected number, got function
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:643: in function 'resolve_bufnr'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:677: in function 'request'
        .../share/nvim/lazy/roslyn.nvim/lua/roslyn/lsp_commands.lua:74: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I installed `roslyn` (and also `rzls` as a custom registry in Mason).

My configs:
```
return {
  {
    -- enabled = false,
    -- 'jmederosalvarado/roslyn.nvim',
    'seblj/roslyn.nvim',
    vscode = false,
    ft = "cs",
    opts = {},
  }
}

```

**Comment by seblj** [comment]
Hmm, it seems like an error I experienced earlier today when trying to implement some hacky stuff in the plugin...

What version of neovim do you have? I suspect this is due to a change where neovim removed support for `client.request` and instead depending on `client:request`. It should have been backwards compatible from what I now...

**Comment by Sverre-W** [comment]
I've seem to have a similar error when the lsp starts:
`LSP[roslyn]: Error SERVER_REQUEST_HANDLER_ERROR: "/usr/share/nvim/runtime/lua/vim/lsp/client.lua:643: bufnr: expected number, got function"`

I'm running neovim _0.10.2_

**Comment by seblj** [comment]
Okay. I think this is an issue after something I did here... I will try to get it fixed fast, but in the meantime you could probably pin it to this commit: 6af7414

**Comment by seblj** [comment]
Does this work for you? https://github.com/seblj/roslyn.nvim/pull/107

**Comment by blamcodes** [comment]
Hi @seblj! Sorry, had a crazy day at work and didn't get a chance to check back here. I gave it a try and it looks like you have fixed the issue I was having - am able to perform the code actions. Thanks for the quick reply and turn around!

**Comment by seblj** [comment]
No problem! Thanks for checking
