### ISSUE TITLE
[Question] Builtin AutoUpdater

### ISSUE THREAD

**Issue by Crashdummyy** [seblj/roslyn.nvim#11]
Hi there

It's way too annoying to get the latest releases.

I built a [public repository](https://github.com/Crashdummyy/roslynLanguageServer) that will download new releases once a day.

Would you accept a PR where it'd check for updates and/or download install them directly like the old integration does with `:CSInstall` ?

**Comment by seblj** [comment]
Interesting... Ideally, I would like to not have any lua code dealing with downloading the language server. Personally, I think I would prefer it we could get it into the mason registry.

I tried to look a bit into that myself actually a couple of days ago, but I couldn't find an easy way without doing something like creating a github repo that downloads new releases.

So what I would prefer, is that one of us tries to create a PR to mason to see if they would accept a PR. I think in the first place, we should _not_ add it to mason-lspconfig, because that would then be included in trying to automatically setup the language server with nvim-lspconfig if a user is using the `setup_handlers`. I would then of course fix the path for mason download in this repo for it to _just_ work

What do you think?

**Comment by seblj** [comment]
Yes, when I tried to look into getting it to mason, I saw that there was several packages that seemed to be annoying to download, so someone created a github repo which crawls it to download. Then they would use that github repo to provide to mason, and from what I could understand, it would then just work with the `PURL` spec that mason is using.

So I think we can just point mason to your repo for downloading

**Comment by seblj** [comment]
I can look into sending a PR to mason that downloads from your repo😄 I'll use this issue as a tracker, and can provide updates here

**Comment by seblj** [comment]
> How'd you go about providing weird hacks in the default configuration?

What do you mean? If I am open to including this hack or?

I am not so familiar with semantic tokens and the specs for it. Could you explain a bit about why it is needed to patch it?
I am open to include something like this if I can understand it a bit more and know why we do it😄

BTW: Already started looking into adding it to mason, and it is going great as of now! Could you do me a favour though? Could you also crawl for osx-x64 and win-arm64? It seems to be normal to also provide those.

Other than that, I think I have something working locally now

**Comment by SimonSchwendele** [comment]
> > How'd you go about providing weird hacks in the default configuration?
> 
> What do you mean? If I am open to including this hack or?
> 
> I am not so familiar with semantic tokens and the specs for it. Could you explain a bit about why it is needed to patch it? I am open to include something like this if I can understand it a bit more and know why we do it😄
> 
> BTW: Already started looking into adding it to mason, and it is going great as of now! Could you do me a favour though? Could you also crawl for osx-x64 and win-arm64? It seems to be normal to also provide those.
> 
> Other than that, I think I have something working locally now

Oh no problem I'll add those in a sec.

The highlight doesn't work as Roslyn doesnt implement `textDocuments/semantic tokens/full`.
This just patches range to be exposed as full.

https://github.com/neovim/neovim/pull/26500

**Comment by seblj** [comment]
Ahaa, I understand! I can look into adding that hack as a built in support :)

**Comment by seblj** [comment]
Thank you! I opened this: https://github.com/mason-org/mason-registry/pull/6330 so lets hope it gets accepted and is merged soon😄

**Comment by seblj** [comment]
I started looking into adding support for semantic tokens without you needing to have the snippet you sent in your config. It seems to work okay, but I need to think a little bit more about it and how I should do it, because it seems to be a bit buggy sometimes🤔
<img width="267" alt="image" src="https://github.com/seblj/roslyn.nvim/assets/5160701/28dcccd3-b346-4bd4-bb35-c81153fa3917">

At first it seemed to be like that until I started to edit the text or do `:e`, but now all of a sudden it seems to correct itself after a second or so.

I need to play with it a little bit to see how it behaves before I decide if I have to add a config for this or not, or if it should be enabled by default or not

**Comment by ADIX7** [comment]
Just a note, with the patch above (added to on_attach) breaks https://github.com/Wansmer/symbol-usage.nvim

**Comment by ADIX7** [comment]
I managed to fix this. There is a 4th parameter for client.request, buffer number, that also has to be passed.
This is the updated snippet.

```lua
if not client.is_hacked_roslyn then
    client.is_hacked_roslyn = true

    -- let the runtime know the server can do semanticTokens/full now
    if client.server_capabilities.semanticTokensProvider then
        client.server_capabilities = vim.tbl_deep_extend("force", client.server_capabilities, {
            semanticTokensProvider = {
                full = true,
            },
        })
    end

    -- -- monkey patch the request proxy
    local request_inner = client.request
    client.request = function(method, params, handler, req_bufnr)
        if method ~= vim.lsp.protocol.Methods.textDocument_semanticTokens_full then
            return request_inner(method, params, handler, req_bufnr)
        end

        local function find_buf_by_uri(search_uri)
            local bufs = vim.api.nvim_list_bufs()
            for _, buf in ipairs(bufs) do
                local name = vim.api.nvim_buf_get_name(buf)
                local uri = "file://" .. name
                if uri == search_uri then
                    return buf
                end
            end
        end

        local doc_uri = params.textDocument.uri

        local target_bufnr = find_buf_by_uri(doc_uri)
        local line_count = vim.api.nvim_buf_line_count(target_bufnr)
        local last_line = vim.api.nvim_buf_get_lines(target_bufnr, line_count - 1, line_count,
            true)[1]

        return request_inner("textDocument/semanticTokens/range", {
                textDocument = params.textDocument,
                range = {
                    ["start"] = {
                        line = 0,
                        character = 0,
                    },
                    ["end"] = {
                        line = line_count - 1,
                        character = string.len(last_line) - 1,
                    },
                },
            },
            handler,
            req_bufnr
        )
    end
end
```

**Comment by Syndim** [comment]
While waiting for the PR to be merged in mason-registry, I created a custom registry that can be used to install roslyn from mason. Just add the `registries` config to mason's setup and you will be able to install roslyn:

```
require('mason').setup({
        registries = {
            'github:mason-org/mason-registry',
            'github:syndim/mason-registry'
        },
    })
```

**Comment by Syndim** [comment]
> > While waiting for the PR to be merged in mason-registry, I created a custom registry that can be used to install roslyn from mason. Just add the `registries` config to mason's setup and you will be able to install roslyn:
> > ```
> > require('mason').setup({
> >         registries = {
> >             'github:mason-org/mason-registry',
> >             'github:syndim/mason-registry'
> >         },
> >     })
> > ```
> 
> That's cool :) I currently just retain the last 15 releases which ammounts to 3-4 weeks regarding their current velocity. Do I need to explicitly retain the pinned version in your registry or do you plan to update every 2 weeks or sth. like this anyways ?

I setup a bot to automatically update the package version. Currently it's sending PRs to the repo, will try to let the bot commit to the repo directly so no action will be needed.

**Comment by Wordluc** [comment]
> While waiting for the PR to be merged in mason-registry, I created a custom registry that can be used to install roslyn from mason. Just add the `registries` config to mason's setup and you will be able to install roslyn:
> 
> ```
> require('mason').setup({
>         registries = {
>             'github:mason-org/mason-registry',
>             'github:syndim/mason-registry'
>         },
>     })
> ```

if i use that, i am able to manually install roslyn,but it gives me an error :
`[mason-lspconfig.nvim] Server "roslyn" is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.`

do you have some ideas? thanks

**Comment by molostovvs** [comment]
@Syndim 
Hi! it seems your feed is out of sync with the microsoft feed - your feed hasn't had an update in 2 weeks. Do you know about this?

**Comment by kmoschcau** [comment]
Hi, I have a small patch to suggest for the semantic tokens. I can't clone or edit the wiki, so I'm doing it here. You only have to add some `vim.fs.normalize` calls to `find_buf_by_uri` to make it work on Windows file systems and with relative paths.

```lua
    local function find_buf_by_uri(search_uri)
      local bufs = vim.api.nvim_list_bufs()
      local normalized_search_uri = vim.fs.normalize(search_uri)
      for _, buf in ipairs(bufs) do
        local name = vim.api.nvim_buf_get_name(buf)
        local uri = vim.fs.normalize("file://" .. name)
        if uri == normalized_search_uri then
          return buf
        end
      end
    end
```

**Comment by Syndim** [comment]
> @Syndim Hi! it seems your feed is out of sync with the microsoft feed - your feed hasn't had an update in 2 weeks. Do you know about this?

> > @Syndim Hi! it seems your feed is out of sync with the microsoft feed - your feed hasn't had an update in 2 weeks. Do you know about this?
> 
> I guess renovate isn't configured correctly. Roslyn bumped from 4.12 to 4.13.

Fixed

**Comment by seblj** [comment]
> Hi, I have a small patch to suggest for the semantic tokens. I can't clone or edit the wiki, so I'm doing it here. You only have to add some `vim.fs.normalize` calls to `find_buf_by_uri` to make it work on Windows file systems and with relative paths.
> 
> 
> 
> ```lua
> 
>     local function find_buf_by_uri(search_uri)
> 
>       local bufs = vim.api.nvim_list_bufs()
> 
>       local normalized_search_uri = vim.fs.normalize(search_uri)
> 
>       for _, buf in ipairs(bufs) do
> 
>         local name = vim.api.nvim_buf_get_name(buf)
> 
>         local uri = vim.fs.normalize("file://" .. name)
> 
>         if uri == normalized_search_uri then
> 
>           return buf
> 
>         end
> 
>       end
> 
>     end
> 
> ```
> 
> 
> 
> Side note: The semantic highlighting seems to do a large amount of requests, noticeably slowing down everything after inserting some characters.

I'll try to update the tips and tricks

**Comment by nagaohiroki** [comment]
> > Hi, I have a small patch to suggest for the semantic tokens. I can't clone or edit the wiki, so I'm doing it here. You only have to add some `vim.fs.normalize` calls to `find_buf_by_uri` to make it work on Windows file systems and with relative paths.

If you change find_buf_by_uri to vim.uri_to_bufnr, it will work on Windows too. I think it will be simpler.

local target_bufnr = find_buf_by_uri(params.textDocument.uri)
↓
local target_bufnr = vim.uri_to_bufnr(params.textDocument.uri)

**Comment by seblj** [comment]
So a little update:

I have used a shell script for a while to automatically update roslyn for me, and that works pretty good for me at least. However, I understand the wish to get it into mason. It seems like it will not be merged into mason shortly, and as a workaround for this, I am thinking about including something like this: https://github.com/seblj/roslyn.nvim/pull/80

It should automatically set up mason with the additional registry from @Syndim. What do you think about this approach?

**Comment by seblj** [comment]
Okay, I think it makes sense to use your fork then as you then have both the repo that automatically gets updates, and also the registry then. Would you be okay with me using that in the PR i linked?

**Comment by seblj** [comment]
Perfect!

**Comment by seblj** [comment]
So I just merged a PR which automatically sets up the registry for mason if mason is installed. While I wished that mason could include it in their original registry, I think this should for the moment at least make it a lot easier for user, and is now also kind of a "builtin autoupdater". So I think therefore I will close this issue as completed for now!

Thanks for maintaining the autoupdater and mason registry! Really appreciate it!
