### ISSUE TITLE
Roslyn target stops server if no option is selected

### ISSUE THREAD

**Issue by nm-marques** [seblj/roslyn.nvim#112]
If you use the Roslyn target to select the solution and you don't select any, because for example you changed your mind, i think the behaviour should be that nothing happens. Instead it stops the server. If you use something like telescope ui select this will be a common occurrence. 

![image](https://github.com/user-attachments/assets/5b3827e5-ec1d-4390-9ee9-13e5a3aeea26)

**Comment by seblj** [comment]
Absolutely. I never use the target command myself so thought it worked as expected. Will fix

**Comment by seblj** [comment]
Can you test this: https://github.com/seblj/roslyn.nvim/pull/114

**Comment by seblj** [comment]
I don't have the same problem btw using my own vim.ui.select and the built in one

**Comment by nm-marques** [comment]
> Can you test this: #114

Can confirm no longer happens, using telescope ui select aswell
