### ISSUE TITLE
csharp_ls question

### ISSUE THREAD

**Issue by searleser97** [seblj/roslyn.nvim#118]
How is this different than just installing 

https://github.com/razzmatazz/csharp-language-server through mason and lspconfig

**Comment by seblj** [comment]
It is a different server. This is using the same server as the C# dev kit in vscode is using

**Comment by searleser97** [comment]
Thanks for answering, after experimenting a bit with it, I feel is much faster and more consistent with Visual Studio 2022 diagnostics which is nice.
