### ISSUE TITLE
Getting rid of "Press ENTER or type command to continue"?

### ISSUE THREAD

**Issue by PaddiM8** [seblj/roslyn.nvim#121]
Every time I open neovim in a C# project, I get this:
```
Initializing Roslyn client for /home/paddi/projects/elk/elk.sln
Press ENTER or type command to continue
```

and have to press enter to continue, which is quite annoying. Is it possible to get rid of it?

**Comment by seblj** [comment]
Yes there are several ways:

- You can update to nightly neovim and configure `messagesopt` which is a new option to disable the press enter to continue
- Set `cmdheight` to 2 for example
- Install a plugin/write yourself something to override `vim.notify` to show it in a popup or something like fidget.nvim
- I can probably add an option to silent all the notifications like that. If so I will add a utility wrapper that calls vim.notify` if the option is off.

What do you prefer?

**Comment by PaddiM8** [comment]
Ohh can't wait for messagesopt! I guess cmdheight is good enough for now then. Takk!

**Comment by dssste** [comment]
May I ask still for the option to silent all the notifications? Or maybe just reduce the amount of messages. At the current stage it is kind of spammy even using popups. (I see a lot of "restoring" related messages)

**Comment by seblyng** [comment]
I have slowly come around for adding an option for silencing the output made by this plugin in case it is still of interest...

Note that it won't silence _everything_, but I don't think it should. The only one that are silenced is the ones that print during initialization. The other ones should only happen if the user does some action that errors, or something that is notifying about requiring user action to function properly

https://github.com/seblyng/roslyn.nvim/pull/240
