### ISSUE TITLE
Using Windows' MSBuild for .NET Framework from WSL breaks Predefined System.* and Package References

### ISSUE THREAD

**Issue by Hazellie** [seblj/roslyn.nvim#124]
I'm not even sure if this is an issue that could be solved with the plugin, but after hours of research, I'm kind of stumped. I know I'm being a stubborn bonehead with a niche and silly use case, but I'm too far in to give up now.

Unfortunately, I have to work with .NET Framework, which limits my options quite a bit in Linux land (albeit, through WSL, so I can leverage the underlying Windows install).

Until yesterday, I was able to use mono to run unit tests fine, however, for some god forsaken reason, Microsoft's .NET Framework implementation of their Azure SDK relies on a library that resides in ntdll.dll, so I was left with two choices - rewrite the tiny bit of code (currently tiny) that interfaces with Azure using a Http client with my own implementation (bit silly) or just build the solution and projects using the underlying windows version of dotnet.exe, I chose the latter.

Everything builds and even runs fine, but Roslyn does not like what is generated one bit:

![image](https://github.com/user-attachments/assets/d81ebadc-9cf6-4653-a08e-363cbd7d3569)

**Comment by Hazellie** [comment]
Found a solution for my specific use case - just used .NET 8 for my unit tests project, kept the libraries to be tested as .NET Framework 4.6.2 and switched to xUnit.v3, surprisingly, it all works and Roslyn has no issues with it.

**Comment by seblj** [comment]
Okay, I think I am going to close this issue then :)
