### ISSUE TITLE
Diagnostic messages is not shown

### ISSUE THREAD

**Issue by helto4real** [seblj/roslyn.nvim#16]
Hi and thank you for making this. 

I saw previous issue with diagnostics not showing. I have problem that it is not showing at all. I tested with the version `4.12.0-1.24355` of roslyn. I tried with `4.11.3` also, same result.

Tried it editing text first but still not showing.

I use Neovim v10.

Thanks!

**Comment by seblj** [comment]
I cannot reproduce this, so I would need a minimal config with an example project I can check with.

**Comment by ADIX7** [comment]
I use 4.12.0-1.24352.3+eab4f6b917edd86d39a3a262907a2c409dc5f489 and diagnostics work for me.

**Comment by helto4real** [comment]
Thanks I will

**Comment by helto4real** [comment]
Of some reason restarting my computer and using the latest version now works, sorry to have wasted your time. Thanks for looking into this. Again thank you for your time making this plugin, I love the fact I can use NVIM with C# development.
