### ISSUE TITLE
Razor/cshtml syntax support

### ISSUE THREAD

**Issue by jariz** [seblj/roslyn.nvim#17]
Support for razor files.

Going to try to get the ball rolling on this fork. [See previous discussion.](https://github.com/jmederosalvarado/roslyn.nvim/issues/32).
As stated over there, roslyn _should_ theoretically already support this.

**Comment by seblj** [comment]
Personally, I am not interested in implementing this. I would however accept a PR for this :)

**Comment by kericsson-dotnet** [comment]
https://github.com/tris203/rzls.nvim/ may be of interest. Still in very early state ( see https://github.com/tris203/rzls.nvim/issues/2 ) but I managed to get it to attach and provide some code actions.

**Comment by InfinytRam** [comment]
hi @Crashdummyy, 

did you have a chance to try [cutlass.nvim](https://github.com/rpollard00/cutlass.nvim) to see if it works?

**Comment by InfinytRam** [comment]
@Crashdummyy, it doesnt seem to be working from my end as well.

Running `:LspInfo` in neovim does not show any LSP clients inside a .Razor file. :(

**Comment by ChuufMaster** [comment]
@Crashdummyy I've found a problem in your fork [cutlass](https://github.com/Crashdummyy/cutlass.nvim) in that it uses `vim.lsp.start_client` instead of `vim.lsp.start` this causes a new client to be started regardless if there is a client that already exists

**Comment by ChuufMaster** [comment]
> > @Crashdummyy I've found a problem in your fork [cutlass](https://github.com/Crashdummyy/cutlass.nvim) in that it uses `vim.lsp.start_client` instead of `vim.lsp.start` this causes a new client to be started regardless if there is a client that already exists
> 
> 
> 
> Yeah the fork is borked I need to remove it.
> 
> I already fixed some other things as well but theres currently not enough implemented-
> 
> At this moment this plugin can't be used as a daily driver :/

Yea I realized after a while that it just behaves unusually due to it using some weird stuff with virtual buffers and it also attaching multiple lsps to the same buffer. I did have a look at the c# dev kit extension for vscode to see if it's not possible to reverse engineer how the lsp works there or something along those lines

**Comment by neubaner** [comment]
I started working on my fork of [https://github.com/tris203/rzls.nvim](rzls.nvim). I was able to make the Razor LSP communicate with the Roslyn LSP and got hover working properly :smile:.

[![asciicast](https://asciinema.org/a/Z3VARCYecxAB0eGhltKxytR0z.svg)](https://asciinema.org/a/Z3VARCYecxAB0eGhltKxytR0z)

I'm trying to tackle completions now but it's been a challenge...

**Comment by jdrupal-dev** [comment]
@neubaner How have you configured roslyn.nvim and rzls.nvim to get that to work?

**Comment by neubaner** [comment]
@jdrupal-dev Take a look at https://github.com/tris203/rzls.nvim. @tris203 and I are actively working on, but it's still under construction.

**Comment by jdrupal-dev** [comment]
Thank you, I provided some details here: https://github.com/tris203/rzls.nvim/issues/3#issuecomment-2449174105
Maybe you can figure out why it's not working (I am using the latest version of both plugins)?

**Comment by seblj** [comment]
Closing this issue as there is an alternative: https://github.com/tris203/rzls.nvim
