### ISSUE TITLE
Cannot nagivate across decompilde code

### ISSUE THREAD

**Issue by franroa** [seblj/roslyn.nvim#18]
Hi, thank you for maintaining this. Best lsp for C#.
I only missing the option of jumping across decompilde code. Is there a way of doing that?
I have managed to configure another cool plugin that allows me that (omnisharp-extended-lsp) but here I have no idea how.

Would be really thankful for your time!

**Comment by seblj** [comment]
I am not sure🤔 Could you share how you did it with `omnisharp-extended-lsp`, then maybe I can take a look

**Comment by ilyasakin** [comment]
@seblj I don't know about `omnisharp-extended-lsp` but maybe this one can help: https://github.com/Decodetalkers/csharpls-extended-lsp.nvim

**Comment by marcinjahn** [comment]
Csharp-ls uses ILSpy for decompilation, they implement the LSP server wrapping Roslyn (and ILSpy)

**Comment by seblj** [comment]
Does vscode handle this?

**Comment by franroa** [comment]
I think it doesn't

**Comment by seblj** [comment]
It looks like it provides hover and some small things, but I couldn't go to definition for example. I will see if there is some easy thing I can do for this to have the same functionality if it is just starting the server in a different way for example.

However, I will not be adding some special logic using ILSpy, as this is meant to be a small wrapper to start the server (as it is off-spec), and also minimal implementation of some custom commands like fix all and such

**Comment by seblj** [comment]
Latest commits should make it somewhat work. Similar (or identical) to how vscode works

**Comment by franroa** [comment]
Cool! Really good job!
