### ISSUE TITLE
"Roslyn server stopped" on open, no LspLogs on WSL

### ISSUE THREAD

**Issue by nmiguel** [seblj/roslyn.nvim#28]
When attempting to open a .cs file I get the message "roslyn server stopped" immediately. `:LspLog` shows nothing regarding Roslyn.
Here is my config
``` 
			{
				"seblj/roslyn.nvim",
				config = function()
					require("roslyn").setup({
						config = {
							-- settings = {
							-- 	["csharp|inlay_hints"] = {
							-- 		csharp_enable_inlay_hints_for_implicit_object_creation = true,
							-- 		csharp_enable_inlay_hints_for_implicit_variable_types = true,
							-- 		csharp_enable_inlay_hints_for_lambda_parameter_types = true,
							-- 		csharp_enable_inlay_hints_for_types = true,
							-- 		dotnet_enable_inlay_hints_for_indexer_parameters = true,
							-- 		dotnet_enable_inlay_hints_for_literal_parameters = true,
							-- 		dotnet_enable_inlay_hints_for_object_creation_parameters = true,
							-- 		dotnet_enable_inlay_hints_for_other_parameters = true,
							-- 		dotnet_enable_inlay_hints_for_parameters = true,
							-- 		dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
							-- 		dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
							-- 		dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
							-- 	},
							-- },
						},
					})
				end,
			},
```

I'm on WSL, and the LSP has been downloaded and verified correctly, with version: `4.8.0-3.23451.1+3686f3061a9202260a0de4d06e91855b0fa21e8c`
I'm using Linux-x64 but have also tried with Win-x86. It might be of note that attempting to run the LSP using `dotnet Microsoft.CodeAnalysis.LanguageServer.dll` returns the following error:
```
Option '--logLevel' is required.
Option '--extensionLogDirectory' is required.
```

**Comment by seblj** [comment]
Try to download the latest version of the server. I don't know what else it can be.

Regarding running the server from the command line. The error messages are pretty clear. I am using those options in the plugin when running the server

**Comment by nmiguel** [comment]
That fixed it, for some reason downloading the package without a platform gives you an older version. I figured you were probably using those flags, but it could be relevant.

Thanks
