### ISSUE TITLE
Fails on macOS: libe_sqlite3.dylib can't be opened

### ISSUE THREAD

**Issue by iamim** [seblj/roslyn.nvim#30]
Shortly after the LSP server starts I start getting a macOS pop up saying:
"libe_sqlite3.dylib" can't be opened because Apple cannot check it for malicious software.

Is there a way to fix it without requiring the user to disable security settings?
<img width="253" alt="image" src="https://github.com/user-attachments/assets/fccccd0f-e8bd-4b72-99ce-cdd1f3a46e08">

**Comment by johndalloxx** [comment]
`sudo xattr -r -d com.apple.quarantine ./libe_sqlite3.dylib`

**Comment by seblj** [comment]
Sorry I forgot to respond to this. I am not sure. I have noticed this myself and it is indeed a bit annoying. However, I believe that this is not something I could do anything with
