### ISSUE TITLE
LazyVim isn't adding keybindings

### ISSUE THREAD

**Issue by Kurren123** [seblj/roslyn.nvim#31]
[From what I can see](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/lsp.lua#L27), I think LazyVim uses the `LspAttach` event to add it's [keybindings](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/lsp/keymaps.lua#L25) such as goto reference, code action etc. Is the `LspAttach` event getting fired by this plugin?

**Comment by seblj** [comment]
I don't know how that specific method wrapping the autocmd is used in LazyVim, but yes. `LspAttach` is called. This is not something I am doing. Neovim is doing all of this when a server attaches
