### ISSUE TITLE
[Question] Setup help

### ISSUE THREAD

**Issue by GustavEikaas** [seblj/roslyn.nvim#33]
I dont really understand how to set this up. Im using lazy.nvim and this is my config

```lua
return {
  "seblj/roslyn.nvim",
  config = function()
    require("roslyn").setup({
      config = {},
      exe = {
        "dotnet",
        vim.fs.joinpath(vim.fn.stdpath("data"), "roslyn", "Microsoft.CodeAnalysis.LanguageServer.dll"),
      },
      filewatching = true,
    })
  end
}

```

The plugin is recognized and setup by lazy
The CodeAnalysis dll is present and the path is verified correct.
Nvim version: V0.10.1

Is there any more steps needed? Do i need to configure the lsp or is that handled under the hood? When I run LspInfo in a .cs buffer I see no roslyn or no error messages

**Comment by marcinjahn** [comment]
You can have a look at [my dotfiles](https://github.com/marcinjahn/dotfiles/blob/main/dot_config/nvim/lua/plugins/roslyn-nvim.lua)

**Comment by seblj** [comment]
Shouldn't need to do anything else. You don't need to provide those values to the setup method though as all of them are the default values. However, impossible to say what is wrong. If there is a solution file/csproj file, then it should work

**Comment by GustavEikaas** [comment]
Seems lazy got confused when I changed from the original repo to this fork and checkout out an old commit. After forcing the latest commit on main the lsp seems to try to start but immediately when entering a file there is a notification saying "Roslyn server stopped" Any ideas? lsp.log is empty

**Comment by seblj** [comment]
Difficult to say. I would think that the lsp log should contain something. Or at least of you set the log level to trace, then it should

**Comment by GustavEikaas** [comment]
I tried modifying the library code and the server starts and the first RPC message is being sent, but it seems to stop the server with an exit code: 0 right after

**Comment by GustavEikaas** [comment]
When starting the server i get this rpc message

```json
{ 
  jsonrpc = "2.0", 
  method = "window/logMessage",
  params = { 
    message = "[Program]Language server initialized", 
    type = 3                                                                                                                                  
  }  
}
```

Looking through the code it seems to look for the "pipeName" property. Should this have been sent as part of the server start. in my case it does not

**Comment by seblj** [comment]
What version of the server do you have?

**Comment by GustavEikaas** [comment]
I was using the latest from this feed: https://dev.azure.com/azure-public/vside/_artifacts/feed/vs-impl

I fixed the issue by downloading the vscode c# extension, digging through the files and finding the dlls for the language server then copying them into nvim-data/roslyn

**Comment by seblj** [comment]
Hmm, I instead want to fix the potential issue then🤔 I have a VM with windows that I can try setting this up with

**Comment by fgimian** [comment]
I'm having the exact same issue here on Windows 11 Pro, and the solution that @GustavEikaas suggested also worked for me.

I downloaded **Microsoft.CodeAnalysis.LanguageServer.4.8.0-3.23451.1.nupkg.zip** and extracted **content\LanguageServer\win-x64** to the correct **roslyn** directory but nothing happens at all when opening a C# project.

However, replacing the roslyn directory with that found in **~\.vscode\extensions\ms-dotnettools.csharp-2.45.20-win32-x64\.roslyn** worked perfectly.

Any ideas what's going on?

Cheers
Fotis-
