### ISSUE TITLE
Better Hover Experience - Feature Request

### ISSUE THREAD

**Issue by tuliopaim** [seblj/roslyn.nvim#36]
In the "original" repo [EnochMtzR](https://github.com/EnochMtzR) opened a PR (https://github.com/jmederosalvarado/roslyn.nvim/pull/30) to improve the hover experience by adding markdown support and replacing some characters. Before switching to this repo I used a fork with his commits and it was great.

Yesterday I tried to adapt it to this new code base, but I have no idea how. If someone could point me in the right direction I could try to do it myself.

**Comment by seblj** [comment]
Doesn't this just work out of the box for you?

**Comment by tuliopaim** [comment]
> Doesn't this just work out of the box for you?

![image](https://github.com/user-attachments/assets/a58ea216-ff9f-46a4-bb0f-a9d16149a421)

**Comment by seblj** [comment]
Are you sure you are using treesitter and have the markdown inline parser? It should just work

**Comment by tuliopaim** [comment]
I confess that I didn't have `markdown_inline`, but now I do and the behavior is the same, what am I missing?

:TSInstallInfo

```
markdown           [✓] installed
markdown_inline    [✓] installed
```

**Comment by seblj** [comment]
What version og neovim do you have?

**Comment by tuliopaim** [comment]
> What version og neovim do you have?

NVIM v0.10.1

**Comment by tuliopaim** [comment]
Someone else commented in that PR asking him to re-implement it here, so it's not only me.

**Comment by seblj** [comment]
I know, but it _should_ just work. So we need to figure out why it doesn't for you. It works for me at least in my config.

I can test with a very minimal config when I have some time

**Comment by seblj** [comment]
<img width="760" alt="image" src="https://github.com/user-attachments/assets/23e89f0b-8b28-4f83-88c5-b3a6502fcbf7">

```lua
for name, url in pairs({
	roslyn = "https://github.com/seblj/roslyn.nvim",
	cattpuccin = "https://github.com/catppuccin/nvim",
	treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
}) do
	local install_path = vim.fn.fnamemodify("roslyn_minimal/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

local path = vim.fs.normalize("~/.local/share/nvim/roslyn/Microsoft.CodeAnalysis.LanguageServer.dll")

require("roslyn").setup({
	exe = { "dotnet", path },
})

require("nvim-treesitter.configs").setup({
	ensure_installed = { "c_sharp" },
})

require("catppuccin").setup()

vim.cmd.colorscheme("catppuccin")
```

This is the default experience with this minimal config.

It is using treesitter markdown_inline parser and setting conceallevel to 2 automatically. However, if you set the conceallevel to 0 (which is the default in all other buffers), then it will look like this:

<img width="761" alt="image" src="https://github.com/user-attachments/assets/1e370dbd-49c7-4990-a9ba-27e000e7e524">

So this must be a config issue

**Comment by drzbida** [comment]
Content format is indeed already markdown and it should work as expected. This can be tested by attaching such a handler in the setup config

```lua
handlers = {
    ["textDocument/hover"] = function(err, result, ctx, config)
        vim.notify(vim.inspect(result.contents.kind), vim.log.levels.INFO)
        vim.lsp.handlers["textDocument/hover"](err, result, ctx, config)
    end,
},
```

That being said, something is definitely wrong with the \ characters that appear before some symbols (even in the first screenshot from last comment). 

![image](https://github.com/user-attachments/assets/55a332fd-4147-4b87-b15d-ab0364910131)
or
![image](https://github.com/user-attachments/assets/e40709d2-7fea-438d-aad6-1f01300005a6)

This is the markdown value intercepted like this:

```lua
  ["textDocument/hover"] = function(err, result, ctx, config)
      vim.notify(vim.inspect(result.contents.value), vim.log.levels.INFO)
      vim.lsp.handlers["textDocument/hover"](err, result, ctx, config)
  end,

```
```plaintext
```csharp\r\nreadonly struct System.Single\r\n```\r\n\r\nRepresents a single\\-precision floating\\-point number\\.\r\n
```

It seems that the server probably sends escapes in code using four \\ instead of two. I'm not entirely sure this should be fixed by this plugin as it is outside the scope and most likely a bug in roslyn, although it definitely is weird to leave it like this.

Here is a temporary fix you can use in your configs:

```lua
return {
    "seblj/roslyn.nvim",
    config = function()
        require("roslyn").setup {
            config = {
                on_init = function(client)
                    client.offset_encoding = "utf-8"
                end,
                handlers = { -- this is what matters
                    ["textDocument/hover"] = function(err, result, ctx, config)
                        if result and result.contents and result.contents.value then
                            result.contents.value = result.contents.value:gsub("\\([^%w])", "%1")
                        end
                        vim.lsp.handlers["textDocument/hover"](err, result, ctx, config)
                    end,
                },
            },
        }
    end,
    lazy = false,
}
```

**Comment by seblj** [comment]
Yeah, I will not be adding a hack for this, as this should be fixed either in the markdown parser queries or in roslyn

**Comment by tuliopaim** [comment]
I appreciate the time spent on this, I'll try to do some research and revisit all my plugins to see if anything could be getting in the middle of this, I tried @drzbida  approach, and it's indeed printing "markdown" as the kind.
I also tried to set the conceallevel to 2 by hand, but with no success.

**Comment by tuliopaim** [comment]
Ok, the issue was the treesitter version, working as expected after updating from v0.9.1 to v0.9.2.

Thanks again @seblj and @drzbida
