### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by drzbida** [seblj/roslyn.nvim#38]
## Motivation

I've tried various C# language servers over the last few weeks, and it seems to me that the combination of Roslyn with this client is the most stable and produces the best results. I would love for this project to become the "standard" in the future, attracting as many users as possible for centralized issue tracking and support. Since C# in Neovim is already a niche within a niche, I believe centralizing efforts would be highly beneficial.

### My Suggestions

In no particular order, here are my suggestions:

1. **Clarify the Purpose of the Fork**: In the introduction, explain why this is a fork and imply that this is currently the only active repository. This will help users understand the importance and relevance of this project.
  
2. **Refine the Requirements Section**: Remove the "requires Neovim 0.10" from the introduction and move it to a separate "Requirements" header. In that section, mention that the Roslyn language server must be installed, and include a hyperlink to a page explaining how to install it. Also, include a link to the relevant Mason PR so that people can engage with it and help bring more attention to it.

3. **Add a Short Demo**: Under the introduction, include a short demo (30-60 seconds) displaying key features such as diagnostics, inlay hints, references, hover, code actions, etc. This would give potential users a quick overview of what they can expect from a working setup. This is the most important section in my opinion. 

4. **Minimal Plugin Installation Instructions**: Provide minimal options for plugin installation instructions using `lazy.nvim`. This will make it easier for users to get started with the plugin, especially considering the rise in popularity of neovim "distributions", which makes people transitioning from other tooling less likely to know how to install this. Also even for experienced users sometimes it's nice to just copy paste something 😄 

5. **Create a Configuration Section**: Add a separate section for configuration, along with the default settings used. This will make it easier for users to understand how to customize the plugin to their needs.

### Example Friendly READMEs

For reference, here are some example READMEs that I find particularly user-friendly:

- [echasnovski/mini.indentscope](https://github.com/echasnovski/mini.indentscope)
- [folke/todo-comments.nvim](https://github.com/folke/todo-comments.nvim)
- [lewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)
- [folke/which-key.nvim](https://github.com/folke/which-key.nvim)

I'm willing to create a PR for any of these suggestions that you agree with if you don't want to deal with it!

**Comment by seblj** [comment]
Yes a PR would be very welcomed😄
