### ISSUE TITLE
LSP is started in single file mode under Windows because the `root_dir` is nil

### ISSUE THREAD

**Issue by Syndim** [seblj/roslyn.nvim#44]
I found that when using this plugin under Windows, the roslyn LSP is always started in single file mode even when I have solution/csproj files.

After some debugging I found that it's because that when detecting `root_dir`, we are passing the full path of the sln file to `vim.fs.root`[here](https://github.com/seblj/roslyn.nvim/blob/f9ca1ae8d95bd7988ad68b49c80370901e7d26f3/lua/roslyn/init.lua#L247C44-L247C52). But somehow it doesn't work under Windows(on my machine I always get `nil`).

From vim's document, it looks we can just pass the file name. I have a try locally to only pass the file name of the sln file and then `root_dir` can be detected correctly and roslyn won't run under single file name any more.

Here is the change I made locally: https://github.com/Syndim/roslyn.nvim/commit/9f8704cdc20ccfa304523b3570481ea29ed8f02f.

**Comment by seblj** [comment]
Interesting🤔 I pushed a change that should fix it
