### ISSUE TITLE
Sometimes sends wrong buffer to vim.lsp.start 

### ISSUE THREAD

**Issue by svermeulen** [seblj/roslyn.nvim#47]
If you open a c# file then immediately change to a different buffer, then vim will use the file type of whatever the new buffer is when initializing the server, resulting in server exitting immediately, if the new buffer is not another cs file.

One fix is to change the lsp_start method to cache the bufnr and pass this to vim.lsp.start like this:

```
   local bufnr = vim.api.nvim_get_current_buf()
    server.start_server(cmd, config, function(pipe_name)
        config.cmd = vim.lsp.rpc.connect(pipe_name)
        local client_id = vim.lsp.start(config, {
            bufnr = bufnr
        })
```

**Comment by seblj** [comment]
That makes sense. Will fix soon
