### ISSUE TITLE
issue on start watcher 

### ISSUE THREAD

**Issue by konstantin-mohin** [seblj/roslyn.nvim#49]
runtime/lua/vim/_watch.lua#L72

it fails on the assert 
`local _, start_err = handle:start(path, uvflags, function(err, filename, events)`

`    assert(not err, err)`

am using the 

`{`
`    "seblj/roslyn.nvim",`
`    ft = "cs",`
`    opts = {}`
`}`

and I do see a message that The server init with a solution and after a while it spams with the error

**Comment by seblj** [comment]
Probably the same reason as this: https://github.com/seblj/roslyn.nvim/issues/48

Set `filewatching` to false in the setup function

**Comment by konstantin-mohin** [comment]
@seblj confirmed.
