### ISSUE TITLE
Newer Microsoft.Roslyn.LanguageServer versions do not show diagnostics

### ISSUE THREAD

**Issue by marcinjahn** [seblj/roslyn.nvim#5]
The README suggests to use the latest version of Mirosoft.CodeAnalysis.LanguageServer from MS feed. At the time of writing, it's version [4.12.0-1.24327.4](https://dev.azure.com/azure-public/vside/_artifacts/feed/vs-impl/NuGet/Microsoft.CodeAnalysis.LanguageServer.linux-x64/overview/4.12.0-1.24327.4).

The server gets initialized, I am able to execute Go To Definition/Implementation, however, the diagnostic messages no longer show up. I can write code that will not compile, and no errors will show up. 

The version that I'm using right now is 4.9.0-3.23604.10, it seems to work pretty well.

**Comment by seblj** [comment]
I am not able to reproduce this with the latest server. Do you have a repo I could try it with?

**Comment by marcinjahn** [comment]
@seblj I just tried the whole thing again, and you're right, it does work. The thing that got me though, is that on the newer version (4.12....) it doesn't load diagnostics until I insert any character.
On version 4.9.. I'm starting to see the diagnostic messages maybe 3 seconds tops after I open my simple 3-file solution console app. And I don't have to do anything else than opening the file. With the new server (I tried a few times now), it never starts automatically. I have to enter any characters first, and only then it starts to work. Odd.

Sounds like some case for `hacks.lua` :smile:

**Comment by seblj** [comment]
Does it load diagnostics for 4.9 with the latest commit before going into insert mode? Because I remember I also stumbled upon that, but that was early in my refactoring of this, and I didn't bother to look into if it was because of some refactoring I did, or if it was issue with the server

**Comment by marcinjahn** [comment]
Well, now I'm confused myself, because I just switched back to 4.9 and it requires something to be inserted now as well... At this point, I'm no longer sure whether it loaded without insert or not :confused:

**Comment by seblj** [comment]
My initial thought at the time was that it was something with `vim.lsp.start`, because if I remember correctly, it started happening around the time I started to use that🤷‍♂️

**Comment by KoushikSahu** [comment]
I am seeing the issue where I need to edit the file before I can see diagnostics. Is there any hack around this? @marcinjahn / @seblj

**Comment by seblj** [comment]
https://github.com/seblj/roslyn.nvim/wiki/Tips-and-tricks

**Comment by KoushikSahu** [comment]
@seblj What's the recommendation for the event here? Basically I want the diagnostics to start appearing right after the roslyn initialization completes.

**Comment by seblj** [comment]
Hmm, I am not sure. I think I need to emit a special event, as there is no event that it is finished. Give me a couple of minutes and I can push something

**Comment by KoushikSahu** [comment]
> Hmm, I am not sure. I think I need to emit a special event, as there is no event that it is finished. Give me a couple of minutes and I can push something

You are one hell of a maintainer man. Really appreciate it, thanks!

**Comment by seblj** [comment]
Thanks! I just pushed a change that should just request diagnostics when the project reloads. I didn't really see any reason to not do it, and I have gotten several questions about this, so instead of creating an event for it, and letting users do this, I just do it in the plugin

However, if you want it to update even more often, then you could use that trick😄

**Comment by KoushikSahu** [comment]
> Thanks! I just pushed a change that should just request diagnostics when the project is finished loading. I didn't really see any reason to not do it, and I have gotten several questions about this, so instead of creating an event for it, and letting users do this, I just do it in the plugin
> 
> However, if you want it to update even more often, then you could use that trick😄

Thanks! Just used the latest commit and it works. This officially makes neovim better than vscode for me :)

**Comment by seblj** [comment]
The only downside is that `vim.lsp.util._refresh` is a "private" method, and is therefore not considered as part of the public API. This means that neovim core could potentially just do whatever they like with it. We'll just deal with it then if something happens to that method😄
