### ISSUE TITLE
LSP performance issues

### ISSUE THREAD

**Issue by daver32** [seblj/roslyn.nvim#52]
I'm not sure if this is just a me problem, but the LSP is an absolute performance hog, to the point of becoming unusable, even on a small solution (5k LOC). Every time I edit the buffer, the CPU usage goes up to 100% and stays there for a few seconds, as if the LSP was reindexing everything on every keystroke.

When trying it in Vscode with the C# Dev Kit, it runs perfectly smooth. 

I've looked through my nvim config and found out some plugins were bombarding the LSP with requests. Disabling these helped somewhat, but it's still nowhere near ideal.

I wonder, am I the only one having this problem? I'd appreciate any pointers.

**Comment by seblj** [comment]
Set `filewatching = false` in the setup method
