### ISSUE TITLE
lsp seems doens't use event about file

### ISSUE THREAD

**Issue by Wordluc** [seblj/roslyn.nvim#54]
When i create a file.cs on nvim, lsp wont return errors.

**Comment by Wordluc** [comment]
sorry, basically when i create a file (from either neotree and netrw ) in neovim of type cs, roslyn doesn't return error, it gives the suggestions but not the error(so the diagnostic).
this is my configuration:
`
require("roslyn").setup({
	filewatching=false,
	config = {
		cmd = {
			"dotnet",
			vim.fs.joinpath(vim.fn.stdpath("data"), "roslyn", "Microsoft.CodeAnalysis.LanguageServer.dll"),
		},
		settings = {
			["csharp|inlay_hints"] = {
				csharp_enable_inlay_hints_for_implicit_object_creation = true,
				csharp_enable_inlay_hints_for_implicit_variable_types = true,
				csharp_enable_inlay_hints_for_lambda_parameter_types = true,
				csharp_enable_inlay_hints_for_types = true,
				dotnet_enable_inlay_hints_for_indexer_parameters = true,
				dotnet_enable_inlay_hints_for_literal_parameters = true,
				dotnet_enable_inlay_hints_for_object_creation_parameters = true,
				dotnet_enable_inlay_hints_for_other_parameters = true,
				dotnet_enable_inlay_hints_for_parameters = true,
				dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
				dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
				dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
			},
			["csharp|code_lens"] = {
				dotnet_enable_references_code_lens = true,
			},
		}
	}

})
`

**Comment by Wordluc** [comment]
this is the issue of the parent: https://github.com/jmederosalvarado/roslyn.nvim/issues/27

**Comment by seblj** [comment]
Seems to be because of `filewatching = false` in your setup function. That is really a hack to not make the server choke on large codebases and is not the default value.

(You could also remove the `config.cmd` option if you like, as that is the default value)
