### ISSUE TITLE
Always running in single file mode

### ISSUE THREAD

**Issue by georgepetersmith** [seblj/roslyn.nvim#59]
I have been unable to get roslyn.nvim running over a project or solution. Instead, it will always run in single file mode.
I have tried specifying the solution file name in `choose_sln` and specifying the root directory in the `config` section, but these steps did not change anything.

I can confirm that `vim.g.roslyn_nvim_selected_solution` is set to the expected solution path: `C:/Users/me/code/test/test.sln`

`:LspInfo` prints the following

> LSP configs active in this buffer (id=1)
> Language client log: ~\AppData\Local\nvim-data\lsp.log
> Detected filetype: cs
> 1 client(s) attached to this buffer
> Client: roslyn (id: 1, bufnr: [1])
> filetypes:
> root directory:  Running in single file mode.
> cmd:  ~\code\test\source\<function>
> autostart: false 

OS: Windows 11
Current commit: 11168911d35ea276b1fbd8fa33f7564325b6c624

**Comment by seblj** [comment]
Are you sure that it doesn't work over the entire solution and just LspInfo is wrong?

**Comment by georgepetersmith** [comment]
On further inspection, this was caused by the on_attach function that sets the keybinds not being called in my configuration. Apologies for the false alarm.
