### ISSUE TITLE
The server exits very quickly without errors after starting

### ISSUE THREAD

**Issue by kmoschcau** [seblj/roslyn.nvim#63]
Hi,

when the plugin tries to start the server, it is able to and even gets the "Language server initialized" response from the server, but the server process exits soon after. This is happening on Windows. The plugin is trying to run this command:

```ps1
dotnet C:\Users\KaiMoschcau\AppData\Local\nvim-data/roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel=Information --extensionLogDirectory=C:/Users/KaiMoschcau/AppData/Local/nvim-data
```

It then soon after gets this response:

```
Content-Length: 115

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"[Program]Language server initialized"}}
```

Then, not even a second later the server process exits without any errors.

When I run the same command from a powershell session, the server process stays alive until I manually terminate it.

I also tried changing the `logLevel` parameter of the manual command to `Debug`, which gave me some more output from the server. When I tried to do the same thing with the command run from the plugin, I noticed that this plugin provides a wrong option to the `vim.system` call. It should be `stderr`, not `stderr_handler`. Sadly I only get the same debug messages from the server here, than when I try to start it manually. (The messages are only about adding solution level analyzers to the workspace.)

I also noticed that the plugin tries to parse the stdout stream as JSON, which seems to fail because of the Content-Length header.

Edit: Here's the version of the server: `4.8.0-3.23451.1+3686f3061a9202260a0de4d06e91855b0fa21e8c`

**Comment by seblj** [comment]
Hmmm, difficult to say what could be wrong, but it seems like you have a very old version of the server. I myself have `4.13.0-1.24508.7+55a809f91cae01bf1e6c635ee91faae6b0af23fe`

Without knowing how old the version is, it could potentially be a version where they are not providing the `pipeName` as json to let the client know how to communicate with the server, so as a first step I would try to update to the newest version of the server. I will generally advice you to update the server regularly as I am mostly targeting the newest version of the server.

Let me know if you still have an issue after updating. If you still have the issue then, it would be great if you could set the log level for neovim with `vim.lsp.set_log_level(0)`, and the send the output of `:LspLog`

Thanks for letting me know about `stderr_handler`. I don't think I have ever really made sure that worked as expected, and it might also be something left from when I originally forked this that I forgot to change. Will fix that now

**Comment by kmoschcau** [comment]
Thanks for the hint and I now realize my mistake. I downloaded the nuget package with the exact name as mentioned in the readme of this project, not one with the arch suffix. The one I downloaded had subfolders for all architectures in it, so I didn't even question it.
![image](https://github.com/user-attachments/assets/05b09fe4-f44a-45ff-a6c9-f50f0a5c29f1)

Anyway it works now and it's so much faster than OmniSharp. I'll close this ticket.

Just a side question: Is there a way to get semantic highlighting working? That's the only thing missing from OmniSharp that I can see at the moment.

**Comment by seblj** [comment]
Yes: https://github.com/seblj/roslyn.nvim/wiki/Tips-and-tricks#semantic-tokens

I just haven't added this as a hack into the plugin as I am waiting for neovim to support it instead. I was thinking about adding it, but last time I tried it, it was a bit buggy. But I think maybe the snippet has been updated since I tested it, and maybe it works better now🤷‍♂️
