### ISSUE TITLE
Keymaps for LSP hops

### ISSUE THREAD

**Issue by Sverre-W** [seblj/roslyn.nvim#65]
Hi, I've managed to install this plugin on a lunarvim setup. I have suggetions and autocomplete working.

 But what keymaps are available? In the video is see LSP hops are available but I don't know how to jump since 'gd' is not working.

Is their additional configuration I need to add to make this work?

**Comment by seblj** [comment]
You (or lunarvim) are probably just defining the keymaps in an on_attach method that is passed into the servers that are setup via lspconfig. You should instead just use `:h LspAttach` autocmd. Or just define the keymaps regardless of attaching to a server.

You could potentially also pass the `on_attach` callback in the setup method of this plugin, but the most easy thing is to just use the `LspAttach` autocmd.

**Comment by seblj** [comment]
You can see an example of this here:
https://github.com/seblj/dotfiles/blob/cac86c289a10c97b43fb00ad47c4c6aa72fc949b/nvim/lua/config/lspconfig/init.lua#L10
