### ISSUE TITLE
Feature request: code action to add static keyword

### ISSUE THREAD

**Issue by quantum-booty** [seblj/roslyn.nvim#67]
This code action is available with Omnisharp, maybe Roslyn has the same capability?
e.g.
```
namespace csharp;

public class Program
{
    public void Main()
    {
        var test = Test();
        Console.WriteLine(test);
    }

    private List<int> Test()
    {
        return [];
    }
}
```
![image](https://github.com/user-attachments/assets/9f021896-60f6-48ba-beb2-d4066c480dc7)

**Comment by seblj** [comment]
I have no idea🤷‍♂️ You can maybe check the README for some options, or this: https://github.com/dotnet/vscode-csharp/blob/main/test/lsptoolshost/unitTests/configurationMiddleware.test.ts

This issue is more suited for the server itself, as I don't do anything with the code actions
