### ISSUE TITLE
on_attach not invoked

### ISSUE THREAD

**Issue by Crashdummyy** [seblj/roslyn.nvim#8]
Hi there

I've got some trouble setting this up.

My config looks like this with `monkeyPatchSemanticTokens` containing [this workaround](https://github.com/jmederosalvarado/roslyn.nvim/issues/34#issuecomment-2148707502)

but it looks like my on_attach never gets called.
```lua
{
  "seblj/roslyn.nvim",
  event = "User csFile",
  config = function()
    require("roslyn").setup({
      dotnet_cmd = "dotnet", -- this is the default
      roslyn_version = "4.12.0-1.24329.2", -- this is the default
      exe = vim.fs.joinpath(
        vim.fn.stdpath("data") --[[@as string]],
        "roslyn",
        "Microsoft.CodeAnalysis.LanguageServer.dll"
      ),
      on_attach = function(client)
        utils.notify("attached")
        utils_lsp.monkeyPatchSemanticTokens(client)
      end
    })
  end
}
```

However  it appears like on_attach is never called.
Am I missing something here ?

**Comment by seblj** [comment]
You can do this:
```lua
{
    "seblj/roslyn.nvim",
    event = "User csFile",
    config = function()
        require("roslyn").setup({
            config = {
                on_attach = function(client)
                    utils.notify("attached")
                    utils_lsp.monkeyPatchSemanticTokens(client)
                end,
            },
        })
    end,
}

```

**Comment by seblj** [comment]
The two first options you pass in is never used in my fork of the plugin, and the `exe` option is the same as the default, so it is also not needed

**Comment by seblj** [comment]
Also, you need to update to the latest commit I just pushed, since I wasn't passing along `on_attach` from the config until now
