### ISSUE TITLE
Can't seem to get LSP started on Windows

### ISSUE THREAD

**Issue by fingolfin19** [seblj/roslyn.nvim#84]
I have followed the manual install instructions and `dotnet ~\AppData\Local\nvim-data\roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --version` works: `4.8.0-3.23451.1+3686f3061a9202260a0de4d06e91855b0fa21e8c`  

But I can't seem to get the lsp to start when opening a .cs file. There are no logs or errors, but `vim.lsp.getclients()` is an empty table. 

I'm using Mini.Deps to install and my config is:

```lua
now(function()
	add("seblj/roslyn.nvim")
	require("roslyn").setup({
		exe = {
			"dotnet",
			vim.fs.joinpath(vim.fn.stdpath("data"), "roslyn", "Microsoft.CodeAnalysis.LanguageServer.dll"),
		},
		args = {
			"--logLevel=debug",
			"--extensionLogDirectory=" .. vim.fs.dirname(vim.lsp.get_log_path()),
		},
	})
end)
```

After opening program.cs I  `:e` again to see if that triggers the autocmd, but it does not work. `:Roslyn restart` doesn't seem to do anything either. Starting the language server from the command line with the same arguments runs without issues.

**Comment by seblj** [comment]
Do you have mason? If so, could you try installing it through that and just remove the config you pass in?

**Comment by fingolfin19** [comment]
I don't normally use mason because I've had problems with it on Windows in the past, but this seems to work. I remove the config, do `:MasonInstall roslyn` and then the LSP starts as expected. I might keep mason just for this as it's quite a bit easier than the manual install.

**Comment by seblj** [comment]
Yeah, manual installation is super annoying...

Happy to hear it working then!
