### ISSUE TITLE
Allow LSP to start in absence of a solution file

### ISSUE THREAD

**Issue by ppebb** [seblj/roslyn.nvim#87]
This was brought up on the original repository in this issue: https://github.com/jmederosalvarado/roslyn.nvim/issues/7.

Given that this was never implemented, I would like to bring attention to it again. I do not mind doing it myself as long as the feature is welcome, but I wanted to clarify first before submitting a PR.

**Comment by seblj** [comment]
I have already been supporting that for months?

**Comment by mparq** [comment]
It looks like a recent change may have broken this behavior (I ran into this too). I pushed a PR to fix it - not too familiar with this codebase but the change seems pretty contained.

**Comment by seblj** [comment]
Ah of course that makes sense. I just quickly looked at your PR and I made a mistake in my refactoring.

Will check it more out later after work

**Comment by seblj** [comment]
Sorry for the bug! Should be fixed now
