### ISSUE TITLE
Wrong root predicted if inside symlinked directory

### ISSUE THREAD

**Issue by brandonpollack23** [seblj/roslyn.nvim#97]
For the purposes of sharing code in a monorepo, I utilize symlinks in a unity project.

There may be better solutions, but this lets me work on multiple projects and edit the shared code all at once. 

If I open a NON symlinked file first, roslyn starts up just fine (especially if I select the target) and works ok.

If I open a symlinked file first that isn't true.

I think the culprit is the line using the buffer for the root, when perhaps it should detect the file and the root aren't the same and at worst prompt? or respect symlinked directories somehow?

https://github.com/seblj/roslyn.nvim/blob/8d66ba0b1237fae19d88d7a09d35ae49e295d8ea/lua/roslyn/init.lua#L42

**Comment by seblj** [comment]
Could you try #98 ?

**Comment by brandonpollack23** [comment]
Figured it out!  I was opneing the file wrong, since smart-open couldn't follow symlinks (patch out) i had to open with find-files which searched git and opened the original directory, and therefore broke stuff.

**Comment by brandonpollack23** [comment]
Thanks for responding so quickly!!!!
